// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdjbwfubyisezfprpqiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkamJ3ZnVieWlzZXpmcHJwcWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODU2NjMsImV4cCI6MjA3MjI2MTY2M30.fQC21bfxHt1FUL3MgtlK5USb0-ISqXOitHTzW3PBEQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});